# Reference: https://eksctl.io/usage/creating-and-managing-clusters/
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# us-east-1 US East (N. Virginia)
# us-east-2 US East (Ohio)
# us-west-2 US West (Oregon) - All 3 have same prices
metadata:
  name: cheapgen
  region: us-east-2

nodeGroups:
  - name: cng-core
    instanceType: t3.medium
    desiredCapacity: 1
    volumeSize: 4
    volumeType: gp2
    labels:
      module: core
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  # - name: cng-extension
  #   instanceType: c5.xlarge
  #   desiredCapacity: 1
  #   labels:
  #     module: extension
  - name: cng-test
    instanceType: t3.medium
    # instanceType: c5.2xlarge
    desiredCapacity: 1
    volumeSize: 4
    labels:
      module: test
  - name: cng-scalar
    instanceType: t3.medium
    # instanceType: c5.4xlarge
    desiredCapacity: 1
    volumeSize: 4
    volumeType: gp2
    labels:
      module: scalar
  - name: cng-grid
    instanceType: t3.medium
    desiredCapacity: 1
    volumeSize: 4
    volumeType: gp2
    labels:
      module: grid
