# Reference: https://eksctl.io/usage/creating-and-managing-clusters/
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wdias-cluster
  region: us-east-2

nodeGroups:
  - name: ng-core
    instanceType: c5.4xlarge
    desiredCapacity: 1
    volumeSize: 21
    volumeType: gp2
    labels:
      module: core
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  # - name: ng-extension
  #   instanceType: c5.xlarge
  #   desiredCapacity: 1
  #   labels:
  #     module: extension
  - name: ng-test
    instanceType: c5n.xlarge
    # instanceType: c5.2xlarge
    desiredCapacity: 1
    volumeSize: 5
    # volumeType: gp2
    labels:
      module: test
