# Reference: https://eksctl.io/usage/creating-and-managing-clusters/
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wdias-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: c5.xlarge
    desiredCapacity: 1
    volumeSize: 10
    volumeType: gp2
    labels:
      datatype: scalar
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: c5.xlarge
    desiredCapacity: 1
    volumeSize: 10
    volumeType: gp2
    labels:
      datatype: grid
    ssh:
      allow: true
