apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: spot-cluster
    region: us-east-1

nodeGroups:
    - name: ng-1
      minSize: 2
      maxSize: 5
      instancesDistribution:
        maxPrice: 0.017
        instanceTypes: ["t3.small", "t3.medium"] # At least two instance types should be specified
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 50
        spotInstancePools: 2