# Reference: https://eksctl.io/usage/creating-and-managing-clusters/
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wdias-cluster
  region: us-east-2

nodeGroups:
  - name: ng-grid
    instanceType: c5.4xlarge
    desiredCapacity: 1
    # minSize: 1
    # maxSize: 2
    volumeSize: 50
    volumeType: gp2
    labels:
      datatype: grid
    ssh:
      allow: true
