# Reference: https://eksctl.io/usage/creating-and-managing-clusters/
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nextgen
  region: us-east-2

nodeGroups:
  - name: ng-scalar
    instanceType: c5.2xlarge
    desiredCapacity: 1
    # minSize: 1
    # maxSize: 2
    volumeSize: 20
    volumeType: gp2
    labels:
      module: scalar
  - name: ng-grid
    instanceType: c5.2xlarge
    desiredCapacity: 1
    # minSize: 1
    # maxSize: 2
    volumeSize: 50
    volumeType: gp2
    labels:
      module: grid